version: 3

tasks:
  install:
    cmds:
      - go mod tidy -v
      - go mod vendor -v

  build:
    cmds:
      - go build -o bin/knit cmd/main.go

  test:
    desc: runs the test suite
    cmds:
      - go test ./...
  
  test:snapshot:
    desc: runs the test suite and updates all snapshots
    env:
      UPDATE_SNAPSHOTS: true
    cmds:
      - go test ./...
    ignore_error: true
