version: 3

tasks:
  ci:
    cmds:
      - task: mod
      - task: build
      - task: test

  mod:
    cmds:
      - go mod tidy -v
      - go mod vendor -v

  build:
    vars:
      GIT_HASH:
        sh: git rev-parse HEAD
    cmds:
      - |
        go build \
          -o bin/knit \
          -ldflags "-X main.commit={{ .GIT_HASH }}" \
          cmd/knit/knit.go

  install:
    cmds:
      - go install cmd/knit/knit.go
  
  uninstall:
    cmds:
      - rm $HOME/go/bin/knit

  test:
    desc: runs the test suite
    cmds:
      - go test -cover ./...
  
  test:snapshot:
    desc: runs the test suite and updates all snapshots
    env:
      UPDATE_SNAPSHOTS: true
    cmds:
      - go test ./...
    ignore_error: true
