version: 3

tasks:
  ci:
    cmds:
      - task: mod
      - task: build
      - task: test

  mod:
    cmds:
      - go mod tidy -v
      - go mod vendor -v

  build:
    cmds:
      - go build -o bin/knit cmd/knit.go

  install:
    cmds:
      - go install cmd/knit.go
  
  uninstall:
    cmds:
      - rm $HOME/go/bin/knit

  test:
    desc: runs the test suite
    cmds:
      - go test -cover ./...
  
  test:snapshot:
    desc: runs the test suite and updates all snapshots
    env:
      UPDATE_SNAPSHOTS: true
    cmds:
      - go test ./...
    ignore_error: true
