name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}
        id: go

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Build
        run: go build -o ./bin/knit ./cmd/knit/knit.go

      - name: Test
        run: go test -cover ./...